### ISSUE TITLE
Error when installing extractnet from pip

### ISSUE THREAD

**Issue by oMateos2020** [currentslab/extractnet#5]
(NLP) C:\Users\omate>pip install extractnet
Collecting extractnet
  Using cached extractnet-1.0.2.tar.gz (12.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\omate\AppData\Local\Temp\pip-install-yv6cl_4d\extractnet_b63eca49657f480f82179438f4f1ce38\setup.py", line 114, in <module>
          ext_modules=cythonize(ext_modules),
        File "c:\users\omate\anaconda3\envs\nlp\lib\site-packages\Cython\Build\Dependencies.py", line 965, in cythonize
          module_list, module_metadata = create_extension_list(
        File "c:\users\omate\anaconda3\envs\nlp\lib\site-packages\Cython\Build\Dependencies.py", line 815, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "c:\users\omate\anaconda3\envs\nlp\lib\site-packages\Cython\Build\Dependencies.py", line 114, in nonempty
          raise ValueError(error_msg)
      ValueError: 'extractnet/lcs.pyx' doesn't match any files
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by theblackcat102** [comment]
Hi, @oMateos2020 the problem should be fixed in latest 2.0.4 version.

**Comment by oMateos2020** [comment]
Thanks @theblackcat102 , I resolved it months ago installing everything on a Linux machine. Anyway those are great news.
